services:
  nats-server:
    image: nats:2.11.6-alpine3.22

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: products-ms
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    environment:
      - PORT=${PRODUCTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - DATABASE_URL_ARG=${ORDERS_MS_DATABASE_URL}
    image: orders-ms
    environment:
      - PORT=${ORDERS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    image: payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: auth-ms
    environment:
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_MS_DATABASE_URL}
      - JWT_SECRET=${AUTH_MS_JWT_SECRET}
      - JWT_EXPIRATION=${AUTH_MS_JWT_EXPIRATION}
