apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: sbsmrth/products-app-payments-ms
        name: products-app-payments-ms
        env:
        - name: PORT
          value: "3003"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: STRIPE_SUCCESS_URL
          value: "http://localhost:3003/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://localhost:3003/payments/cancelled"
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payments-ms-secrets
              key: stripe_secret_key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-ms-secrets
              key: stripe_webhook_secret
        resources: {}
status: {}
